version: 0.0.00
name: 'School Admin'
module:
    name: 'School Admin'
    description: 'Allows administrators to configure school settings.'
    entryURL: academic_year_manage
    type: Core
    active: 'Y'
    category: Admin
    version: 0.0.00
    author: 'Craig Rayner'
    url: 'http://www.craigrayner.com'
    actions:
        'Academic Years':
            name: 'Academic Years'
            precedence: 0
            category: 'Years, Days & Times'
            description: 'Allows user to control the definition of academic years within the system'
            URLList: 'academic_year_manage,academic_year_edit,academic_year_delete,academic_year_add,default'
            entryURL: academic_year_manage
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'N'
            defaultPermissionStudent: 'N'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'N'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'N'
            categoryPermissionParent: 'N'
            categoryPermissionOther: 'N'
            permissions:
                - Administrator
        'Year Groups':
            name: 'Year Groups'
            precedence: 0
            category: Groupings
            description: ''
            URLList: 'year_group_manage,year_group_edit,year_group_add,year_group_delete,year_group_top_of_list'
            entryURL: year_group_manage
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'N'
            defaultPermissionStudent: 'N'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'N'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'N'
            categoryPermissionParent: 'N'
            categoryPermissionOther: 'N'
            permissions:
                - Administrator
        Houses:
            name: Houses
            precedence: 0
            category: Groupings
            description: ''
            URLList: 'house_manage,house_edit,house_add,house_delete,house_assign'
            entryURL: house_manage
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'N'
            defaultPermissionStudent: 'N'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'N'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'N'
            categoryPermissionParent: 'N'
            categoryPermissionOther: 'N'
            permissions:
                - Administrator
        'Days of the Week':
            name: 'Days of the Week'
            precedence: 0
            category: 'Years, Days & Times'
            description: ''
            URLList: days_of_the_week
            entryURL: days_of_the_week
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'N'
            defaultPermissionStudent: 'N'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'N'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'N'
            categoryPermissionParent: 'N'
            categoryPermissionOther: 'N'
            permissions:
                - Administrator
        'Academic Year Terms':
            name: 'Academic Year Terms'
            precedence: 0
            category: 'Years, Days & Times'
            description: ''
            URLList: 'academic_year_term_manage,academic_year_term_edit,academic_year_term_add,academic_year_term_delete'
            entryURL: academic_year_term_manage
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'N'
            defaultPermissionStudent: 'N'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'N'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'N'
            categoryPermissionParent: 'N'
            categoryPermissionOther: 'N'
            permissions:
                - Administrator
        'Special Days':
            name: 'Special Days'
            precedence: 0
            category: 'Years, Days & Times'
            description: ''
            URLList: 'special_day_manage,special_day_add,special_day_edit,special_day_delete,special_day_duplicate'
            entryURL: special_day_manage
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'N'
            defaultPermissionStudent: 'N'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'N'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'N'
            categoryPermissionParent: 'N'
            categoryPermissionOther: 'N'
            permissions:
                - Administrator
        Facilities:
            name: Facilities
            precedence: 0
            category: Other
            description: 'Allows users to create a list of spaces and rooms in the school'
            URLList: 'facility_manage,facility_add,facility_edit,facility_delete'
            entryURL: facility_manage
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'N'
            defaultPermissionStudent: 'N'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'N'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'N'
            categoryPermissionParent: 'N'
            categoryPermissionOther: 'N'
            permissions:
                - Administrator
        'Activity Settings':
            name: 'Activity Settings'
            precedence: 0
            category: Learn
            description: 'Control activity settings'
            URLList: activity_settings
            entryURL: activity_settings
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'N'
            defaultPermissionStudent: 'N'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'N'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'N'
            categoryPermissionParent: 'N'
            categoryPermissionOther: 'N'
            permissions:
                - Administrator
        'Behaviour Settings':
            name: 'Behaviour Settings'
            precedence: 0
            category: People
            description: 'Manage settings for the Behaviour module'
            URLList: behaviour_settings
            entryURL: behaviour_settings
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'N'
            defaultPermissionStudent: 'N'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'N'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'N'
            categoryPermissionParent: 'N'
            categoryPermissionOther: 'N'
            permissions:
                - Administrator
        'Resource Settings':
            name: 'Resource Settings'
            precedence: 0
            category: Learn
            description: 'Manage settings for the resources module'
            URLList: resource_settings
            entryURL: resource_settings
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'N'
            defaultPermissionStudent: 'N'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'N'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'N'
            categoryPermissionParent: 'N'
            categoryPermissionOther: 'N'
            permissions:
                - Administrator
        'Planner Settings':
            name: 'Planner Settings'
            precedence: 0
            category: Learn
            description: 'Edit settings for the planner'
            URLList: planner_settings
            entryURL: planner_settings
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'N'
            defaultPermissionStudent: 'N'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'N'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'N'
            categoryPermissionParent: 'N'
            categoryPermissionOther: 'N'
            permissions:
                - Administrator
        Scales:
            name: Scales
            precedence: 1
            category: Assess
            description: 'Manage all aspects of grade scales, which are used throughout ARR to control grade input.'
            URLList: 'scale_manage,scale_add,scale_edit,scale_delete,scale_grade_manage,scale_grade_add,scale_grade_edit,scale_grade_delete'
            entryURL: scale_manage
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'N'
            defaultPermissionStudent: 'N'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'N'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'N'
            categoryPermissionParent: 'N'
            categoryPermissionOther: 'N'
            permissions:
                - Administrator
        'Alert Levels':
            name: 'Alert Levels'
            precedence: 0
            category: People
            description: 'Manage the alert levels which are used throughout the school to flag problems.'
            URLList: alert_levels
            entryURL: alert_levels
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'N'
            defaultPermissionStudent: 'N'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'N'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'N'
            categoryPermissionParent: 'N'
            categoryPermissionOther: 'N'
            permissions:
                - Administrator
        'Individual Needs':
            name: 'Individual Needs'
            precedence: 0
            category: People
            description: 'Allows admins to control the descriptors available for use in the Individual Needs module.'
            URLList: 'in_manage,in_add,in_edit,in_delete'
            entryURL: in_manage
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'N'
            defaultPermissionStudent: 'N'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'N'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'N'
            categoryPermissionParent: 'N'
            categoryPermissionOther: 'N'
            permissions:
                - Administrator
        'Formal Assessment Settings':
            name: 'Formal Assessment Settings'
            precedence: 0
            category: Assess
            description: 'Configure External Assessment module options'
            URLList: formal_assessment
            entryURL: formal_assessment
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'N'
            defaultPermissionStudent: 'N'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'N'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'N'
            categoryPermissionParent: 'N'
            categoryPermissionOther: 'N'
            permissions:
                - Administrator
        'Markbook Settings':
            name: 'Markbook Settings'
            precedence: 0
            category: Assess
            description: 'Configure options for the Markbook module'
            URLList: markbook_settings
            entryURL: markbook_settings
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'N'
            defaultPermissionStudent: 'N'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'N'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'N'
            categoryPermissionParent: 'N'
            categoryPermissionOther: 'N'
            permissions:
                - Administrator
        'Messenger Settings':
            name: 'Messenger Settings'
            precedence: 0
            category: Other
            description: 'Manage gateway settings for outgoing SMS messages.'
            URLList: messenger_settings
            entryURL: messenger_settings
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'N'
            defaultPermissionStudent: 'N'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'N'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'N'
            categoryPermissionParent: 'N'
            categoryPermissionOther: 'N'
            permissions:
                - Administrator
        'File Extensions':
            name: 'File Extensions'
            precedence: 0
            category: Other
            description: 'Manage file extensions allowed across the system'
            URLList: 'file_extensions_manage,file_extensions_add,file_extensions_edit,file_extensions_delete'
            entryURL: file_extensions_manage
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'N'
            defaultPermissionStudent: 'N'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'N'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'N'
            categoryPermissionParent: 'N'
            categoryPermissionOther: 'N'
            permissions:
                - Administrator
        'Finance Settings':
            name: 'Finance Settings'
            precedence: 0
            category: Other
            description: 'Allows users to edit the text that appears in invoices and receipts.'
            URLList: finance_settings
            entryURL: finance_settings
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'N'
            defaultPermissionStudent: 'N'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'N'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'N'
            categoryPermissionParent: 'N'
            categoryPermissionOther: 'N'
            permissions:
                - Administrator
        'External Assessments':
            name: 'External Assessments'
            precedence: 1
            category: Assess
            description: 'Add, edit and delete external assessments.'
            URLList: 'external_assessments_manage,external_assessment_edit,external_assessment_field_edit,external_assessment_field_delete,external_assessment_delete,external_assessment_add,external_assessment_field_add'
            entryURL: external_assessments_manage
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'N'
            defaultPermissionStudent: 'N'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'N'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'N'
            categoryPermissionParent: 'N'
            categoryPermissionOther: 'N'
            permissions:
                - Administrator
        'Facility Settings':
            name: 'Facility Settings'
            precedence: 0
            category: Other
            description: 'Allows privileged users to manage settings for spaces.'
            URLList: facility_settings
            entryURL: facility_settings
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'N'
            defaultPermissionStudent: 'N'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'N'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'N'
            categoryPermissionParent: 'N'
            categoryPermissionOther: 'N'
            permissions:
                - Administrator
        'Tracking Settings':
            name: 'Tracking Settings'
            precedence: 0
            category: Assess
            description: 'Allows a user to manage settings for the Tracking module.'
            URLList: tracking_settings
            entryURL: tracking_settings
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'N'
            defaultPermissionStudent: 'N'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'N'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'N'
            categoryPermissionParent: 'N'
            categoryPermissionOther: 'N'
            permissions:
                - Administrator
        'Dashboard Settings':
            name: 'Dashboard Settings'
            precedence: 0
            category: Other
            description: 'Manage settings that control Staff, Student and Parent dashboards.'
            URLList: dashboard_settings
            entryURL: dashboard_settings
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'N'
            defaultPermissionStudent: 'N'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'N'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'N'
            categoryPermissionParent: 'N'
            categoryPermissionOther: 'N'
            permissions:
                - Administrator
        'Attendance Settings':
            name: 'Attendance Settings'
            precedence: 0
            category: People
            description: 'Allows administrators to configure the attendance module.'
            URLList: 'attendance_settings,attendance_code_add,attendance_code_edit,attendance_code_delete'
            entryURL: attendance_settings
            entrySidebar: 'Y'
            menuShow: 'Y'
            defaultPermissionAdmin: 'Y'
            defaultPermissionTeacher: 'N'
            defaultPermissionStudent: 'N'
            defaultPermissionParent: 'N'
            defaultPermissionSupport: 'N'
            categoryPermissionStaff: 'Y'
            categoryPermissionStudent: 'N'
            categoryPermissionParent: 'N'
            categoryPermissionOther: 'N'
            permissions:
                - Administrator
